[ColorEffects:Disabled]
Color=#{{colors.on_surface_variant.default.hex_stripped}}
ColorAmount=0
ColorEffect=0
ContrastAmount=0
IntensityAmount=0

[Colors:Button]
BackgroundAlternate={{colors.surface_container_high.default.hex}}
BackgroundNormal={{colors.surface_container.default.hex}}
DecorationFocus={{colors.primary.default.hex}}
DecorationHover={{colors.primary_container.default.hex}}
ForegroundActive={{colors.on_primary.default.hex}}
ForegroundInactive={{colors.on_surface_variant.default.hex}}
ForegroundNormal={{colors.on_surface.default.hex}}

[Colors:Selection]
BackgroundAlternate={{colors.primary_container.default.hex}}
BackgroundNormal={{colors.primary.default.hex}}
DecorationFocus={{colors.primary.default.hex}}
ForegroundActive={{colors.on_primary.default.hex}}
ForegroundInactive={{colors.on_primary.default.hex}}
ForegroundNormal={{colors.on_primary.default.hex}}

[Colors:View]
BackgroundAlternate={{colors.surface_container_low.default.hex}}
BackgroundNormal={{colors.surface.default.hex}}
DecorationFocus={{colors.primary.default.hex}}
DecorationHover={{colors.primary_container.default.hex}}
ForegroundActive={{colors.primary.default.hex}}
ForegroundInactive={{colors.on_surface_variant.default.hex}}
ForegroundNormal={{colors.on_surface.default.hex}}

[Colors:Window]
BackgroundAlternate={{colors.surface_container_low.default.hex}}
BackgroundNormal={{colors.surface.default.hex}}
DecorationFocus={{colors.primary.default.hex}}
DecorationHover={{colors.primary_container.default.hex}}
ForegroundActive={{colors.primary.default.hex}}
ForegroundNegative={{colors.error.default.hex}}
ForegroundInactive={{colors.on_surface_variant.default.hex}}
ForegroundNormal={{colors.on_surface.default.hex}}

[Colors:Tooltip]
BackgroundAlternate={{colors.surface_container.default.hex}}
BackgroundNormal={{colors.surface.default.hex}}
DecorationFocus={{colors.primary.default.hex}}
DecorationHover={{colors.primary_container.default.hex}}
ForegroundActive={{colors.primary.default.hex}}
ForegroundInactive={{colors.on_surface_variant.default.hex}}
ForegroundNormal={{colors.on_surface.default.hex}}

[Colors:Complementary]
BackgroundAlternate={{colors.surface_container_low.default.hex}}
BackgroundNormal={{colors.surface.default.hex}}
DecorationFocus={{colors.primary.default.hex}}
DecorationHover={{colors.primary_container.default.hex}}
ForegroundActive={{colors.primary.default.hex}}
ForegroundInactive={{colors.on_surface_variant.default.hex}}
ForegroundNormal={{colors.on_surface.default.hex}}

[Colors:Header]
BackgroundAlternate={{colors.surface_container_high.default.hex}}
BackgroundNormal={{colors.surface_container.default.hex}}
DecorationFocus={{colors.primary.default.hex}}
DecorationHover={{colors.primary_container.default.hex}}
ForegroundActive={{colors.primary.default.hex}}
ForegroundInactive={{colors.on_surface_variant.default.hex}}
ForegroundNormal={{colors.on_surface.default.hex}}

[General]
ColorScheme=Afloat
Name=Afloat
shadeSortColumn=true

[WM]
activeBackground={{colors.surface_container.default.hex}}
activeBlend={{colors.primary.default.hex}}
activeForeground={{colors.on_surface.default.hex}}
inactiveBackground={{colors.surface_container_low.default.hex}}
inactiveBlend={{colors.outline.default.hex}}
inactiveForeground={{colors.on_surface_variant.default.hex}}
